apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: server
          image: ghcr.io/beekley/home-web-server/monitor:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MON_HOST
              value: monitor-service.default.svc.cluster.local:80
---
apiVersion: v1
kind: Service
metadata:
  name: monitor-service
spec:
  selector:
    app: monitor # Must match deployment label above.
  ports:
    - port: 80 # Internal Cluster Port; What is exposed to the cluster.
      targetPort: 3000 # Container Port; What the server listens on.
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: monitor-discovery
spec:
  clusterIP: None
  selector:
    app: monitor
  ports:
    - port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitor-ingress
  annotations:
    # Enable HTTPS for Monitor too
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    # Auto-generate a certificate for mon.beekley.xyz
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - mon.beekley.xyz
      secretName: monitor-tls-secret
  rules:
    # Explicitly lock this rule to mon.beekley.xyz
    - host: mon.beekley.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitor-service
                port:
                  number: 80
